name: Deploy to GitHub Pages (Self-hosted)

on:
  push:
    branches:
      - main # Oder 'master', je nachdem, welchen Branch du für deine Quelle verwendest

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Oder die Node.js-Version, die du lokal verwendest (z.B. '20')

      - name: Install dependencies
        # Verwende npm ci für eine saubere Installation in CI/CD-Umgebungen
        run: npm ci

      - name: Build React App
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          force_orphan: true